version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:/minio-data:/data
      - ./config:/root/.minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root12345678
      MINIO_CONSOLE_ADDRESS: ":9001"
      MINIO_COMPRESSION_ENABLE: "on"
      MINIO_COMPRESSION_MIME_TYPES: "*"
      MINIO_COMPRESSION_ALLOW_ENCRYPTION: "on"
    command: server /data

volumes:
  minio_storage: {}